// Cards de exemplo para a home (visual premium quando não há imóveis no banco)

export const MOCK_PROPERTIES = [
  {
    id: 'mock-1',
    code: 'IM-2024-001',
    slug: 'apartamento-cobertura-jardins',
    title: 'Cobertura Duplex com Vista Panorâmica',
    type: 'APARTAMENTO',
    purpose: 'VENDA',
    value: 2_850_000,
    city: 'São Paulo',
    neighborhood: 'Jardins',
    rooms: 4,
    bathrooms: 5,
    parking: 3,
    area: 380,
    images: [{ url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800' }],
  },
  {
    id: 'mock-2',
    code: 'IM-2024-002',
    slug: 'casa-moderna-alphaville',
    title: 'Casa Moderna com Piscina e Churrasqueira',
    type: 'CASA',
    purpose: 'VENDA',
    value: 1_950_000,
    city: 'Barueri',
    neighborhood: 'Alphaville',
    rooms: 5,
    bathrooms: 4,
    parking: 4,
    area: 450,
    images: [{ url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800' }],
  },
  {
    id: 'mock-3',
    code: 'IM-2024-003',
    slug: 'apartamento-luxo-moema',
    title: 'Apartamento de Luxo 3 Suítes',
    type: 'APARTAMENTO',
    purpose: 'ALUGUEL',
    value: 12_500,
    city: 'São Paulo',
    neighborhood: 'Moema',
    rooms: 3,
    bathrooms: 4,
    parking: 2,
    area: 165,
    images: [{ url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800' }],
  },
  {
    id: 'mock-4',
    code: 'IM-2024-004',
    slug: 'casa-praia-guaruja',
    title: 'Casa de Praia com Vista para o Mar',
    type: 'CASA',
    purpose: 'ALUGUEL',
    value: 8_000,
    city: 'Guarujá',
    neighborhood: 'Enseada',
    rooms: 4,
    bathrooms: 3,
    parking: 2,
    area: 220,
    images: [{ url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800' }],
  },
  {
    id: 'mock-5',
    code: 'IM-2024-005',
    slug: 'cobertura-pinheiros',
    title: 'Cobertura Exclusiva com Terraço',
    type: 'APARTAMENTO',
    purpose: 'VENDA',
    value: 3_200_000,
    city: 'São Paulo',
    neighborhood: 'Pinheiros',
    rooms: 4,
    bathrooms: 4,
    parking: 2,
    area: 320,
    images: [{ url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800' }],
  },
  {
    id: 'mock-6',
    code: 'IM-2024-006',
    slug: 'casa-familiar-campinas',
    title: 'Casa Familiar em Condomínio Fechado',
    type: 'CASA',
    purpose: 'VENDA',
    value: 1_350_000,
    city: 'Campinas',
    neighborhood: 'Cambuí',
    rooms: 4,
    bathrooms: 3,
    parking: 2,
    area: 280,
    images: [{ url: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800' }],
  },
];
